repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    #-   id: end-of-file-fixer
    #-   id: trailing-whitespace

-   repo: https://github.com/blairdrummond/pre-commit-sandbox
    rev: 58e9af4e3146eca90ff50709fd974b322c837a27
    hooks:
    -   id: malicious
