repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    #-   id: end-of-file-fixer
    #-   id: trailing-whitespace

-   repo: https://github.com/blairdrummond/pre-commit-sandbox
    rev: d97887b7749ee94911895af558a86ff7513f6161
    hooks:
    -   id: malicious
